name: Exercitium2018
version: '0.1.0.0'
synopsis: Exercitium  (Curso 2018-19)
description: >
  Recopilación de soluciones de los problemas propuestos en Exercitium
  durante el curso 2018-19. 
category: Educational
author: Jose A. Alonso
maintainer: JoseA.Alonso@gmail.com
copyright: Jose A. Alonso
license: BSD3
github: jaalonso/Exercitium2018
extra-source-files:
- README.org
dependencies:
  - array >= 0.5
  - directory
  - gnuplot
  - hspec
  - hspec-core
  - matrix 
  - primes
  - QuickCheck >=2.9.2
library:
  source-dirs: src
  ghc-options: -Wall -fno-warn-type-defaults
  dependencies:
  - base >=4.7 && <5
tests:
  spec:
    main: Spec.hs
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - hspec
    - hspec-core
    - Exercitium2018
     
